[project]
name = "building-systems-with-the-chatgpt-api-course"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dotenv==0.9.9",
    "openai==2.13.0",
    "tiktoken==0.12.0",
]
